# Generated by Django 6.0.3 on 2026-04-13 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_automationtask_use_multimodal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_type', models.CharField(choices=[('docx', 'Word文档'), ('pdf', 'PDF文档'), ('md', 'Markdown'), ('txt', '文本文件'), ('xlsx', 'Excel表格')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_docs', to='core.project', verbose_name='所属项目')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='RequirementPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=100, verbose_name='需求ID')),
                ('content', models.TextField(verbose_name='需求内容')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='需求摘要')),
                ('ai_confidence', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='匹配置信度')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='置信度分数')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('covered', '已覆盖')], default='pending', max_length=20, verbose_name='状态')),
                ('linked_case_count', models.IntegerField(default=0, verbose_name='关联用例数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requirements', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='core.testcasemodule', verbose_name='所属模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.project', verbose_name='所属项目')),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ai_requirement_analysis.requirementdoc', verbose_name='来源文档')),
            ],
            options={
                'verbose_name': '需求条目',
                'verbose_name_plural': '需求条目',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='ai_requirem_project_4e8090_idx'), models.Index(fields=['module'], name='ai_requirem_module__0034a9_idx'), models.Index(fields=['ai_confidence'], name='ai_requirem_ai_conf_0c25f2_idx')],
            },
        ),
    ]
