# Generated by Django 6.0.3 on 2026-04-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requirement_analysis', '0001_initial'),
        ('core', '0010_alter_automationtask_use_multimodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('folder', '文件夹'), ('requirement', '需求项')], default='folder', max_length=20, verbose_name='节点类型')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('content', models.TextField(blank=True, default='', verbose_name='需求内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '需求节点',
                'verbose_name_plural': '需求节点',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='requirementpool',
            name='ai_requirem_project_4e8090_idx',
        ),
        migrations.RemoveIndex(
            model_name='requirementpool',
            name='ai_requirem_module__0034a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='requirementpool',
            name='ai_requirem_ai_conf_0c25f2_idx',
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ai_requirement_analysis.requirementnode', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_nodes', to='core.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='ai_requirement_analysis.requirementdoc', verbose_name='来源文档'),
        ),
        migrations.RemoveField(
            model_name='requirementpool',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='requirementpool',
            name='module',
        ),
        migrations.RemoveField(
            model_name='requirementpool',
            name='project',
        ),
        migrations.RemoveField(
            model_name='requirementpool',
            name='source_doc',
        ),
        migrations.AddIndex(
            model_name='requirementnode',
            index=models.Index(fields=['project', 'node_type'], name='ai_requirem_project_063663_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementnode',
            index=models.Index(fields=['project', 'parent'], name='ai_requirem_project_b07116_idx'),
        ),
        migrations.DeleteModel(
            name='RequirementPool',
        ),
    ]
