# Generated by Django 6.0.3 on 2026-03-23 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='知识条目标题')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('vector_id', models.CharField(blank=True, max_length=100, verbose_name='向量ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='测试用例标题')),
                ('description', models.TextField(verbose_name='测试用例描述')),
                ('requirements', models.TextField(blank=True, verbose_name='需求描述')),
                ('code_snippet', models.TextField(blank=True, verbose_name='代码片段')),
                ('test_steps', models.TextField(verbose_name='测试步骤')),
                ('expected_results', models.TextField(verbose_name='预期结果')),
                ('actual_results', models.TextField(blank=True, verbose_name='实际结果')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('approved', '评审通过'), ('rejected', '评审未通过')], default='pending', max_length=20, verbose_name='评审状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('llm_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('bu', models.CharField(blank=True, choices=[('education', '教育'), ('user_center', '用户中心'), ('collaboration', '协同'), ('im', 'IM'), ('workspace', '工作台'), ('recruitment', '招聘'), ('work_management', '工作管理'), ('ai_application', 'AI 应用'), ('operation_platform', '运营平台')], max_length=50, verbose_name='BU')),
                ('feature', models.CharField(blank=True, max_length=100, verbose_name='Feature')),
                ('priority', models.CharField(blank=True, choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], max_length=2, verbose_name='Priority')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_testcases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='TestCaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comments', models.TextField(verbose_name='评审意见')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='评审时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试用例评审',
                'verbose_name_plural': '测试用例评审',
            },
        ),
    ]
