# Generated by Django 6.0.3 on 2026-03-31 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_testcase_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='vector_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='向量 ID'),
        ),
        migrations.CreateModel(
            name='TestCaseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='用例编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('module', models.CharField(choices=[('user_center', '用户中心'), ('education', '教育'), ('collaboration', '协同'), ('im', 'IM'), ('workspace', '工作台'), ('recruitment', '招聘'), ('work_management', '工作管理'), ('ai_application', 'AI 应用'), ('operation_platform', '运营平台'), ('other', '其他')], default='other', max_length=50, verbose_name='模块')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=2, verbose_name='优先级')),
                ('case_type', models.CharField(choices=[('functional', '功能测试'), ('performance', '性能测试'), ('compatibility', '兼容性测试'), ('security', '安全性测试'), ('ui', 'UI 测试'), ('api', '接口测试')], default='functional', max_length=20, verbose_name='用例类型')),
                ('preconditions', models.TextField(blank=True, verbose_name='前置条件')),
                ('test_steps', models.TextField(verbose_name='测试步骤')),
                ('expected_results', models.TextField(verbose_name='预期结果')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('maintainer', models.CharField(blank=True, max_length=100, verbose_name='维护人')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签，多个标签用逗号分隔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_library', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例库',
                'verbose_name_plural': '用例库',
                'ordering': ['-case_number'],
            },
        ),
    ]
