# Generated by Django 6.0.3 on 2026-03-31 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_knowledgebase_vector_id_testcaselibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='模块标识')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.testcasemodule', verbose_name='父模块')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_modules', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例模块',
                'verbose_name_plural': '用例模块',
                'ordering': ['order', 'name'],
            },
        ),
    ]
