# Generated by Django 6.0.3 on 2026-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testcasemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaselibrary',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
