# Generated by Django 6.0.3 on 2026-04-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testcaselibrary_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=100, unique=True, verbose_name='任务UUID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='执行状态')),
                ('execution_mode', models.CharField(choices=[('single', '单用例执行'), ('batch', '批量执行')], default='single', max_length=20, verbose_name='执行模式')),
                ('browser', models.CharField(choices=[('chromium', 'Chrome'), ('firefox', 'Firefox'), ('webkit', 'Safari')], default='chromium', max_length=20, verbose_name='浏览器类型')),
                ('headless', models.BooleanField(default=True, verbose_name='无头模式')),
                ('ai_decision_log', models.TextField(blank=True, verbose_name='AI决策日志')),
                ('use_multimodal', models.BooleanField(default=False, verbose_name='是否使用多模态')),
                ('multimodal_reason', models.TextField(blank=True, verbose_name='多模态使用原因')),
                ('script_path', models.CharField(blank=True, max_length=500, verbose_name='脚本路径')),
                ('report_url', models.CharField(blank=True, max_length=500, verbose_name='Allure报告URL')),
                ('allure_report_path', models.CharField(blank=True, max_length=500, verbose_name='Allure报告路径')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='core.testcaselibrary', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': '自动化执行日志',
                'verbose_name_plural': '自动化执行日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
