# Generated by Django 6.0.3 on 2026-04-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_automation_execution_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('web', 'Web测试'), ('api', '接口测试')], default='web', max_length=10, verbose_name='测试类型')),
                ('config', models.JSONField(default=dict, verbose_name='任务配置')),
                ('use_multimodal', models.BooleanField(default=True, verbose_name='启用多模态视觉分析')),
                ('llm_provider', models.CharField(default='deepseek', max_length=50, verbose_name='LLM提供商')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='任务状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], max_length=20, null=True, verbose_name='最近执行状态')),
                ('total_executions', models.IntegerField(default=0, verbose_name='总执行次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_tasks', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '自动化测试任务',
                'verbose_name_plural': '自动化测试任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCaseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_relations', to='core.testcaselibrary', verbose_name='关联用例')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_relations', to='core.automationtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务用例关联',
                'verbose_name_plural': '任务用例关联',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'case')},
            },
        ),
    ]
