# Generated by Django 6.0.3 on 2026-04-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_automationtask_taskcaserelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=100, unique=True, verbose_name='任务UUID')),
                ('report_path', models.CharField(max_length=500, verbose_name='报告存储路径')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('ERROR', '错误')], max_length=20, verbose_name='报告状态')),
                ('error_log_summary', models.TextField(blank=True, verbose_name='错误日志摘要')),
                ('error_stack_trace', models.TextField(blank=True, verbose_name='错误堆栈信息')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, verbose_name='失败现场截图路径')),
                ('ai_diagnosis', models.TextField(blank=True, verbose_name='AI诊断建议')),
                ('execution_time', models.FloatField(null=True, blank=True, verbose_name='执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务执行报告',
                'verbose_name_plural': '任务执行报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
