# Generated by Django 6.0.3 on 2026-04-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taskexecutionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecutionlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='core.automationtask', verbose_name='关联任务'),
        ),
    ]
