# Generated by Django 6.0.3 on 2026-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_automationexecutionlog_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='use_multimodal',
            field=models.BooleanField(default=False, verbose_name='启用多模态视觉分析'),
        ),
    ]
