# Generated by Django 6.0.3 on 2026-03-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_project_testcase_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('global', '全局配置'), ('project', '项目配置')], default='global', max_length=10, verbose_name='配置类型')),
                ('llm_base_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='LLM API Base URL')),
                ('llm_api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='LLM API Key')),
                ('llm_model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='LLM Model Name')),
                ('vision_base_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vision API Base URL')),
                ('vision_api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vision API Key')),
                ('vision_model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vision Model Name')),
                ('use_global', models.BooleanField(default=True, verbose_name='使用全局配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='core.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'unique_together': {('config_type', 'project')},
            },
        ),
    ]
